### ISSUE TITLE
Unable to stage due to registry connection issues

### ISSUE THREAD

**Issue by paulcwarren** [cloudfoundry-incubator/eirini-release#21] opened 2018-11-12 17:11 UTC
We have an scf+eirini (on GCP and CFCR) that looks like it can stage, but fails at the `Waiting for app to start` step.  We see k8s attempt to pull the image for the app pod from the registry but gets a connection refused error. 

Looking closer.  Possibly related we (also) appear to be hitting an error in the `post-deployment-setup` job at the `Configuring Eirini staging secrets` step. It looks like `kubectl` isn’t able to connect to the kubernetes deployment to transfer the secrets from the scf namespace to the opi namespace. We think that the problem is our `EIRINI_KUBE_CONFIG` in our config-values.yml file, possibly combined with the `kube`.`external_ips` also being wrong. Can you explain these settings a bit more, plus suggest any other debugging tips here. We assume that this `post-deployment-setup` job needs to complete successfully before we will be able to push apps to the platform.  But it is just that, an assumption.

Many thanks

**Comment by mnitchev** [comment] 2018-11-13 15:11
Hi @paulcwarren ,

The `post-deployment-setup` job failing is normal since it’s coming from the templates generated by SCF. Since we add our [eirini.yaml](https://github.com/cloudfoundry-incubator/eirini-release/blob/master/scf/helm/cf/templates/eirini.yaml) template ourselves, the last step in that job: `Configuring Eirini staging secrets ...` won’t execute successfully, but that shouldn’t be an issue. Maybe @viovanov knows more about this and how to fix it.

Regarding the `EIRINI_KUBE_CONFIG`; that value is no longer required. We are getting the kubeconfig from a service account which is part of the [eirini.yaml](https://github.com/cloudfoundry-incubator/eirini-release/blob/master/scf/helm/cf/templates/eirini.yaml#L141) template.

Here are some questions that might help pin down the issue:
1. What values did you set for the `kube.external_ips`? They should be the external ip of each node in your cluster (maybe you set it using the private ones?). 
1. What value are you setting for the `opi.ingress_endpoint`? 
1. Are you deploying using the [scf templates in eirini-release](https://github.com/cloudfoundry-incubator/eirini-release/tree/master/scf)?

Here is what you could check in addition (based on @JulzDiverse's suggestions):
- Are both eirini containers `ready` (ready state shows 2/2)?
- Is the `eirini-opi` service available (`kubectl get service eirini-opi`)
- you could connect to the api pod and try to curl `eirini-opi.scf.svc.cluster.local:8085/apps` to see if you get any response.

BR,
Mario && @suhlig

**Comment by davewalter** [comment] 2018-11-13 16:10
Hi @mnitchev and @suhlig,

Thanks for the quick response. Answers are inline below...

> The `post-deployment-setup` job failing is normal since it’s coming from the templates generated by SCF. Since we add our [eirini.yaml](https://github.com/cloudfoundry-incubator/eirini-release/blob/master/scf/helm/cf/templates/eirini.yaml) template ourselves, the last step in that job: `Configuring Eirini staging secrets ...` won’t execute successfully, but that shouldn’t be an issue. Maybe @viovanov knows more about this and how to fix it.

Good to know, thanks.

> Regarding the `EIRINI_KUBE_CONFIG`; that value is no longer required. We are getting the kubeconfig from a service account which is part of the [eirini.yaml](https://github.com/cloudfoundry-incubator/eirini-release/blob/master/scf/helm/cf/templates/eirini.yaml#L141) template.

Also good to know! Is the service account a GCE account? If so, we don't see one called "opi". If not, where should we check to confirm that it exists?

> Here are some questions that might help pin down the issue:
> 
> 1. What values did you set for the `kube.external_ips`? They should be the external ip of each node in your cluster (maybe you set it using the private ones?).

We tried initially with the external IP of the worker node (we only have one). We then switched to the ephemeral external IP of the `eirini-opi` service to see if that made any difference (it didn't). We have switched back to the worker's external IP.

> 2. What value are you setting for the `opi.ingress_endpoint`?

We have tried a few values here as well. We currently have `eirini-opi.scf.svc.cluster.local`. Do we need to add the port `8085`?

> 3. Are you deploying using the [scf templates in eirini-release](https://github.com/cloudfoundry-incubator/eirini-release/tree/master/scf)?

Yes, we are.

> Here is what you could check in addition (based on @JulzDiverse's suggestions):
> 
> * Are both eirini containers `ready` (ready state shows 2/2)?

Yes, all CF-related containers are ready, except for the post-deployment pod that we now know we can ignore.

> * Is the `eirini-opi` service available (`kubectl get service eirini-opi`)

Yes, we can see that.

> * you could connect to the api pod and try to curl `eirini-opi.scf.svc.cluster.local:8085/apps` to see if you get any response.

We can hit that endpoint. It just gives us an empty desired-lrp response:
```
api/0:/# curl eirini-opi.scf.svc.cluster.local:8085/apps                                                                                                                                                                                                                      │·············································
{"desired_lrp_scheduling_infos":[]}
```

> __Edit:__ Additional questions:
> 
> * Is your cluster a multi-node cluster?

No, we only have a single master and single worker for now.

> * What infrastructure is your cluster deployed on?

We deployed [cfcr](https://github.com/cloudfoundry-incubator/kubo-deployment) on GCP.

> * Are the registry certificates copied on all nodes `/etc/docker/certs.d/<registry-name>/`? (You can check if the [cert-copier](https://github.com/cloudfoundry-incubator/eirini-release/blob/master/scf/helm/cf/templates/eirini.yaml#L183) is a DaemonSet instead of a Job)

No, we have not done that. We were waiting for the post-deployment pod to complete. We can do that step and see what difference it makes.

Let us know if you have any additional thoughts and we'll try the suggestions above.

Thanks again,
@paulcwarren and Dave

**Comment by mnitchev** [comment] 2018-11-22 13:42
Hello @davewalter & @paulcwarren,

Following this [conversation on slack](https://cloudfoundry.slack.com/conversation/C8RU3BZ26/p1542127805141200) we understand that you found a temporary solution to your issue, but the original problem was not solved. We also tested a few configurations in our environments and could not reproduce. Can you give a short recap of your workaround here?

Since we can't really reproduce the issue we're going to go ahead and close it. You can also see [this story in our tracker](https://www.pivotaltracker.com/story/show/161374611) that aims to improve/clarify the opi configurations.

BR,
Mario && @suhlig

**Closed by mnitchev** 2018-11-22 13:42 UTC
Labels: in progress
