### ISSUE TITLE
Failed to push apps in large concurrency with eirini runtime on AKS

### ISSUE THREAD

**Issue by walk1ng** [cloudfoundry-incubator/eirini-release#55] opened 2019-03-27 10:00 UTC
### Description

  On Microsoft AKS, failed to push apps in large concurrency with eirini runtime. Error message from cf cli:
```
Staging app and tracing logs...
Error staging application: Staging error: unable to communicate to compatible cells
FAILED
```
after the failure, cloud foundry won't handle any other app push requests.

the **"large"** is not certain, sometimes concurrency 10 can lead to failure, sometimes it is 20 or more. 

### Steps to reproduce

  Write a script or use tool to concurrently push apps. (```cf push```)

### What was expected to happen

  Push successfully and all apps are running correctly.

### What actually happened

  Push apps failed.

### Suggested fix (optional)

  n/a

### Additional information (optional)

  n/a

**Comment by gdankov** [comment] 2019-04-15 10:05
Hi @walk1ng,

We tried to reproduce the issue on IBM Cloud (since we don't have AKS) and we were unsuccessful. It looks like the problem is related to Diego's staging, so maybe this is an issue for Diego/SCF?

Thanks,
@gdankov & @akshaymankar

**Comment by alex-slynko** [comment] 2019-04-24 10:19
Hi @walk1ng ,

Could you please check it with latest Eirini? We have fixed several issues and Eirini should work better.

**Comment by julz** [comment] 2019-06-20 10:50
Closing this for now, please re-open if there are still problems with latest Eirini - thanks!

**Closed by julz** 2019-06-20 10:50 UTC
Labels: unscheduled
